ignore_phrases = {
    # PowerManage
    "Power Manage": True,
    "PM": True,
    "PowerManage (SmartCut)": True,
    # Panels & Panel Families
    "PowerMaster / PowerMax": True,
    "PowerSeries Neo/Pro, Quazar <5.3": True,
    "IQ Systems": True,
    "Neo": True,
    "PowerMaster": True,
    "Dual Path": True,
    "Qolsys": True,
    "PowerMaster/PowerMax": True,
    "PowerSeries NEO/Pro, Quazar <5.3": True,
    # Devices & etc.
    "PG Box": True,
    "Z-Waves": True,
    "IQRemote": True,
    "Plink": True,
    "Power link": True,
    "GSM Modem": True,
    "OTA Modem": True,
    "Fibro Transmitter": True,
    "Power Master PGM": True,
    "Module AUX 2": True,
    "Proximity Tag": True,
    "PGM %d": True,
    "HSM2Host %d": True,
    "HSM3105MX %d": True,
    "HSM3801 %d": True,
    "HSM3408 %d": True,
    "HSM3105MX": True,
    "HSM2400": True,
    "HSM2955 %d": True,
    "HSM3204CX %d": True,
    "HSM2400 %d": True,
    "HSM3804 %d": True,
    "HSM3702 %d": True,
    "HSM2300 %d": True,
    "HSM2204 %d": True,
    "HSM2208 %d": True,
    "HSM2108 %d": True,
    "HSM2955": True,
    "Wl commander": True,
    "HSM2Host": True,
    "HSM2308 %d": True,
    "HSM3105MX Tamper": True,
    "HSM2400 Tamper": True,
    "HSM2201 %d": True,
    "HSMX56K": True,
    "HSM3204 %d": True,
    "HSM3116 %d": True,
    "HSM3108 %d": True,
    "HSM2100 %d": True,
    "HSM22400": True,
    "2x16 LCD Keypad": True,
    "HSM2955 Tamper": True,
    "HSM3350 %d": True,
    "PGM 2 %d": True,
    "HSMX56K %d": True,
    "GSM %d": True,
    "X10": True,
    "3rd party HA": True,
    "BS8243": True,
    "DD243": True,
    "PGM/X-10": True,
    # Roles
    "Dweller Master": True,
    "Master": True,
    # Communication & Protocols
    "TLS 1.2": True,
    "TLS 1.3": True,
    "HTTP": True,
    "HTTPS": True,
    "HTTPS				": True,
    "Fibro": True,
    "Bluetooth": True,
    "GSM": True,
    "GRPS": True,
    "LWM2M BOOTSTRAP": True,
    "DTLS": True,
    "Gsm Rssi": True,
    "Ethernet": True,
    "PSTN/PTM": True,
    "SMS": True,
    "DLS": True,
    "MB": True,
    "MSG": True,
    "Dls api": True,
    "Dls Api": True,
    "FTP": True,
    "FTPS": True,
    "TFTP": True,
    "LOCAL": True,
    "Dnis": True,
    "7: NB-IoT": True,
    "41: Ethernet": True,
    "42: DSL": True,
    "43: PLC": True,
    "NB-IoT": True,
    "5G-NR TDD": True,
    "5G-NR FDD": True,
    "DSL": True,
    "PLC": True,
    "SMNC": True,
    "SMCC": True,
    "APN": True,
    "PSTN": True,
    "Ssh": True,
    "SSID": True,
    "SSH": True,
    "GSM RSSI": True,
    "USB WIFI": True,
    "USB Wi-Fi": True,
    "TCP/IP": True,
    "WI-FI": True,
    "Wi-Fi": True,
    "IMEI": True,
    "Wifi Ap SSID": True,
    "Port": True,
    "Port:": True,
    "Port: %s": True,
    "Port (${PORT})": True,
    "GPRS": True,
    "USB": True,
    "BBA": True,
    "TLS1": True,
    "SSL 3": True,
    "SSL 2/3": True,
    "SSL": True,
    "Online": True,
    "PowerMaster GPRS": True,
    "2G": True,
    "3G": True,
    "GPRS Up/Down": True,
    "GSM  Up/Down": True,
    "GSM Auto Test": True,
    "GSM Up/Down": True,
    "GSM/GPRS/SMS": True,
    "PSTN Up/Down": True,
    "SIA text": True,
    "SIA": True,
    "TCP": True,
    "UDP": True,
    "Wi-Fi AP": True,
    "SIA Auto": True,
    "CID: Over Cellular/Ethernet": True,
    "Dls": True,
    # Locales
    "en_US": True,
    "fr_CA": True,
    "es_US": True,
    "it_IT": True,
    "nl_NL": True,
    "nb_NO": True,
    "sv_SE": True,
    "is_IS": True,
    "de_DE": True,
    "hu_HU": True,
    "da_DK": True,
    "ro_RO": True,
    "pt_PT": True,
    "fr_FR": True,
    "Bulgarian": True,
    "Chinese": True,
    "Croatian": True,
    "Danish": True,
    "Dutch": True,
    "English": True,
    "Estonian": True,
    "Finnish": True,
    "French": True,
    "German": True,
    "Greek": True,
    "Hebrew": True,
    "Hungarian": True,
    "Italian": True,
    "Latvian": True,
    "Lithuanian": True,
    "Norwegian": True,
    "Polish": True,
    "Portuguese": True,
    "Romanian": True,
    "Russian": True,
    "Serbian": True,
    "Slovakian": True,
    "Slovenian": True,
    "Spanish": True,
    "Swedish": True,
    "Turkish": True,
    "Ukrainian": True,
    # Countries
    "Andorra": True,
    "Angola": True,
    "Argentina": True,
    "Barbados": True,
    "Belize": True,
    "Benin": True,
    "Botswana": True,
    "Burkina Faso": True,
    "Burundi": True,
    "Chile": True,
    "Egypt": True,
    "Eritrea": True,
    "Gabon": True,
    "Ghana": True,
    "Grenada": True,
    "Guatemala": True,
    "Guinea": True,
    "Guinea-Bissau": True,
    "Guyana": True,
    "Haiti": True,
    "Honduras": True,
    "Kiribati": True,
    "Laos": True,
    "Lesotho": True,
    "Malawi": True,
    "Mali": True,
    "Malta": True,
    "Nauru": True,
    "Niger": True,
    "Palau": True,
    "Panama": True,
    "Paraguay": True,
    "Peru": True,
    "Portugal": True,
    "Rwanda": True,
    "Samoa": True,
    "San Marino": True,
    "Senegal": True,
    "Sierra Leone": True,
    "Togo": True,
    "Tonga": True,
    "Tuvalu": True,
    "Uganda": True,
    "Uruguay": True,
    "Vanuatu": True,
    "Venezuela": True,
    "Vietnam": True,
    "Zimbabwe": True,
    "Afghanistan": True,
    "Albania": True,
    "Algeria": True,
    "Antigua and Barbuda": True,
    "Armenia": True,
    "Australia": True,
    "Austria": True,
    "Azerbaijan": True,
    "The Bahamas": True,
    "Bahrain": True,
    "Bangladesh": True,
    "Belarus": True,
    "Belgium": True,
    "Bhutan": True,
    "Bolivia": True,
    "Bosnia and Herzegovina": True,
    "Brazil": True,
    "Brunei": True,
    "Bulgaria": True,
    "Cambodia": True,
    "Canada": True,
    "Cape Verde": True,
    "Central African Republic": True,
    "Chad": True,
    "China": True,
    "Colombia": True,
    "Comoros": True,
    "Congo, Republic of the": True,
    "Congo, Democratic Republic of the": True,
    "Costa Rica": True,
    "Cote d'Ivoire": True,
    "Croatia": True,
    "Cuba": True,
    "Cyprus": True,
    "Czech Republic": True,
    "Denmark": True,
    "Djibouti": True,
    "Dominica": True,
    "Dominican Republic": True,
    "East Timor": True,
    "Ecuador": True,
    "El Salvador": True,
    "Equatorial Guinea": True,
    "Estonia": True,
    "Ethiopia": True,
    "Fiji": True,
    "Finland": True,
    "France": True,
    "The Gambia": True,
    "Georgia": True,
    "Germany": True,
    "Greece": True,
    "Hungary": True,
    "Iceland": True,
    "India": True,
    "Indonesia": True,
    "Iran": True,
    "Iraq": True,
    "Ireland": True,
    "Israel": True,
    "Italy": True,
    "Jamaica": True,
    "Japan": True,
    "Jordan": True,
    "Kazakhstan": True,
    "Kenya": True,
    "Korea, North": True,
    "Korea, South": True,
    "Kuwait": True,
    "Kyrgyz Republic": True,
    "Latvia": True,
    "Lebanon": True,
    "Liberia": True,
    "Libya": True,
    "Liechtenstein": True,
    "Lithuania": True,
    "Luxembourg": True,
    "Macedonia": True,
    "Madagascar": True,
    "Malaysia": True,
    "Maldives": True,
    "Marshall Islands": True,
    "Mauritania": True,
    "Mauritius": True,
    "Mexico": True,
    "Federated States of Micronesia": True,
    "Moldova": True,
    "Monaco": True,
    "Mongolia": True,
    "Morocco": True,
    "Mozambique": True,
    "Myanmar (Burma)": True,
    "Namibia": True,
    "Nepal": True,
    "Netherlands": True,
    "New Zealand": True,
    "Nicaragua": True,
    "Nigeria": True,
    "Norway": True,
    "Oman": True,
    "Pakistan": True,
    "Papua New Guinea": True,
    "Philippines": True,
    "Poland": True,
    "Qatar": True,
    "Romania": True,
    "Russia": True,
    "Saint Kitts and Nevis": True,
    "Saint Lucia": True,
    "Sao Tome and Principe": True,
    "Saudi Arabia": True,
    "Serbia and Montenegro": True,
    "Seychelles": True,
    "Singapore": True,
    "Slovakia": True,
    "Slovenia": True,
    "Solomon Islands": True,
    "Somalia": True,
    "South Africa": True,
    "Spain": True,
    "Sri Lanka": True,
    "Sudan": True,
    "Suriname": True,
    "Swaziland": True,
    "Sweden": True,
    "Switzerland": True,
    "Syria": True,
    "Taiwan": True,
    "Tajikistan": True,
    "Tanzania": True,
    "Thailand": True,
    "Trinidad and Tobago": True,
    "Tunisia": True,
    "Turkey": True,
    "Turkmenistan": True,
    "Ukraine": True,
    "United Arab Emirates": True,
    "United Kingdom": True,
    "United States": True,
    "Uzbekistan": True,
    "Vatican City (Holy See)": True,
    "Yemen": True,
    "Zambia": True,
    "Montenegro": True,
    "South Korea": True,
    # Abbreviation
    "Ok": True,
    "OK": True,
    "Aux": True,
    "PTM": True,
    "EULA": True,
    "SOS": True,
    "E-mail": True,
    "Email": True,
    "PIR": True,
    "x10": True,
    "PGM": True,
    "RSSI": True,
    "RI": True,
    "P": True,
    "PGH": True,
    "ID": True,
    "ssid": True,
    "CSV": True,
    "PDF": True,
    "URL": True,
    "Mmi": True,
    "PGM 1": True,
    "PGM 2": True,
    "PGM 3": True,
    "PGM 4": True,
    "PGM1": True,
    "PGM2": True,
    "PGMs": True,
    "N/A": True,
    "PIN#1": True,
    "PIN#2": True,
    "PIN#3": True,
    "PIN#4": True,
    "PIN#5": True,
    "PIN#6": True,
    "PIN#7": True,
    "PIN#8": True,
    "BOSS": True,
    "RRI": True,
    "FTC": True,
    "CO": True,
    "TLM": True,
    # Metric
    "V": True,
    "mA": True,
    "Ohm": True,
    "AM": True,
    "cid": True,
    "sia": True,
    "lux": True,
    "ar": True,
    "th": True,
    "LI": True,
    "Fahrenheit": True,
    # Variables
    "(%s)": True,
    "%s km": True,
    "%s m": True,
    "%m/%d": True,
    "%H:%M": True,
    "%m/%d %H:%M": True,
    "%d modules": True,
    "%T_POWERG_TRANCEIVER %d": True,
    "%T_MX_DEVICE_EXPANDER %d": True,
    "%T_IO_EXPANDER %d": True,
    "%T_MX_DEVICE_EXPANDER": True,
    "%T_PRINTER": True,
    "%T_AUDIO_VERIFICATION %d": True,
    "%T_BUS_REPEATER %d": True,
    "%T_PRINTER %d": True,
    "%T_DOOR_CONTROL %d": True,
    "%T_POWER_SUPPLY_3A %d": True,
    "%T_FIREBELL %d": True,
    "%T_POWER_SUPPLY %d": True,
    "%T_POWER_SUPPLY_WITH_OUTPUTS %d": True,
    "%T_OUTPUT_EXPANDER %d": True,
    "%T_ZONE_EXPANDER %d": True,
    "%T_AUDIO_VERIFICATION": True,
    "%T_POWERG_TRANCEIVER": True,
    "PGM $(i+1)": True,
    "PGM $(n+1)": True,
    "Camera #%d": True,
    "HSMX 56K": True,
    "HW iov": True,
    "Plink %d": True,
    "Bell Canada %d": True,
    "PGH %d": True,
    "USA (hh:mm AM/PM)": True,
    "X10 $(i+1)": True,
    "PGM $((hsm_2204-1)*4+j+4": True,
    "PGM $((hsm_2208-1)*8+j+36)": True,
    "PGM $((hsm_3204cx-1)*4+j+292)": True,
    "PGM $(panel_pgm)": True,
    "Tel. %d": True,
    "Host (${HOST})": True,
    "Superkeys $i": True,
    # Errors, troubles & notice
    "EpromNotSupported": True,
    "EpromBadValue": True,
    "CheckStatus": True,
    "DeniedAccess": True,
    "ArmedPanel": True,
    "MasterPinRequired": True,
    "Setpin": True,
    "PULL_CONFIGURATION_FIRST": True,
    "OWNER_HAS_A_KEYFOB": True,
    "BAD_PARAMETER": True,
    "TOO_MANY_PACKAGES": True,
    "PROCESS_NOT_FOUND": True,
    "TOO_LATE": True,
    "NOT_SUPPORTED_BY_PANEL": True,
    "AUTO_TIME_SYNC_ENABLED": True,
    "INVALID_PANEL_STATE": True,
    # Masks
    "xxx.xxx.xxx.xxx": True,
    "PPPPPPPPPPPPPPPP": True,
    "TTTTTTTTTTTTTTTT": True,
    # Numeric options
    "+ 1   ": True,
    "+ 2   ": True,
    "+ 3   ": True,
    "- 1   ": True,
    "- 2   ": True,
    "- 3   ": True,
    "- 1": True,
    "- 2": True,
    "- 3": True,
    "+ 1": True,
    "+ 2": True,
    "+ 3": True,
    "4/2 1800/2300": True,
    "4/2 1900/1400": True,
    "7.2V NiMH": True,
    "7.2V": True,
    "9.6V NiMH": True,
    "9.6V": True,
    "UL 20/20": True,
    "100Mbit/s, Full Duplex": True,
    "100Mbit/s, Half Duplex": True,
    "10Mbit/s, Full Duplex": True,
    "10Mbit/s, Half Duplex": True,
    # Options
    "I__voice_box_mode": True,
    "P01: PGM PIN #1": True,
    "P02: PGM PIN #2": True,
    "P03: PGM PIN #3": True,
    "P04: PGM PIN #4": True,
    "P05: PGM PIN #5": True,
    "P06: PGM PIN #6": True,
    "P07: PGM PIN #7": True,
    "P08: PGM PIN #8": True,
    "subType 1": True,
    "subType 10": True,
    "subType 11": True,
    "subType 12": True,
    "subType 13": True,
    "subType 14": True,
    "subType 15": True,
    "subType 16": True,
    "subType 17": True,
    "subType 18": True,
    "subType 19": True,
    "subType 2": True,
    "subType 20": True,
    "subType 21": True,
    "subType 22": True,
    "subType 23": True,
    "subType 24": True,
    "subType 25": True,
    "subType 26": True,
    "subType 27": True,
    "subType 28": True,
    "subType 29": True,
    "subType 3": True,
    "subType 30": True,
    "subType 4": True,
    "subType 5": True,
    "subType 6": True,
    "subType 7": True,
    "subType 8": True,
    "subType 9": True,
    "[2] Tamper": True,
    "[3] Tamper": True,
    "[6] Time Date Mask": True,
    "[393][001] Model": True,
    "PushApp_Ring_CallsDig_CallsVoc_Sms_Rx": True,
    "PushApp_Rx_Ring_CallsDig_CallsVoc_Sms": True,
    "PushApp_Rx_Sms_Ring_CallsDig_CallsVoc": True,
    "PushApp_Sms_Ring_CallsDig_CallsVoc_Rx": True,
    "PushApp_Sms_Rx_Ring_CallsDig_CallsVoc": True,
    "Ring_CallsDig_CallsVoc_Rx_Sms_PushApp": True,
    "Ring_CallsDig_CallsVoc_Sms_Rx_PushApp": True,
    "Rx_Ring_CallsDig_CallsVoc_Sms_PushApp": True,
    "Rx_Sms_Ring_CallsDig_CallsVoc_PushApp": True,
    "Sms_Ring_CallsDig_CallsVoc_Rx_PushApp": True,
    "Sms_Rx_Ring_CallsDig_CallsVoc_PushApp": True,
    "PushApp_Ring_CallsDig_CallsVoc_Rx_Sms": True,
    "[215] GSM Codec Audio": True,
    "[376] SMS NUM $(n)": True,
    "[112] PTM": True,
    "[112] White List": True,
    "[230] Auto SMS": True,
    "[282] DNIS": True,
    "[*][5]": True,
    "anytime/all dev": True,
    "entry/BS devs": True,
    "entry/DD devs": True,
    "entry/all devs": True,
    "entry/wl+awy kp": True,
    # Tunes
    "High Wire": True,
    "On The Hunt": True,
    "Door Bell": True,
    "Heaven": True,
    "Moon Beam": True,
    "Dear Deer": True,
    "Sonar": True,
    "F1 New": True,
    "Tinker Bell": True,
    "Pizzicato": True,
    # Other
    "Software": True,
    "Auto": True,
    "Test": True,
    "Contact ID": True,
    "Server": True,
    "№": True,
    "On/Off": True,
    "Off": True,
    "On": True,
    "Superkeys": True,
    "PartitionId": True
}
