ignore_phrases = {
    # PowerManage
    "Power Manage": True,
    "PM": True,
    # Panels & Panel Families
    "PowerMaster / PowerMax": True,
    "PowerSeries Neo/Pro, Quazar <5.3": True,
    "IQ Systems": True,
    "PowerMaster": True,
    "Dual Path": True,
    "Qolsys": True,
    "PowerMaster/PowerMax": True,
    "PowerSeries NEO/Pro, Quazar <5.3": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    # Devices & etc.
    "PG Box": True,
    "IQRemote": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    # Roles
    "Dweller Master": True,
    "Master": True,
    # Communication & Protocols
    "TLS 1.2": True,
    "TLS 1.3": True,
    "HTTP": True,
    "HTTPS": True,
    "HTTPS				": True,
    "Fibro": True,
    "Bluetooth": True,
    "GSM": True,
    "GRPS": True,
    "LWM2M BOOTSTRAP": True,
    "DTLS": True,
    "Gsm Rssi": True,
    "Ethernet": True,
    "PSTN/PTM": True,
    "SMS": True,
    "DLS": True,
    "MB": True,
    "MSG": True,
    "Dls api": True,
    "Dls Api": True,
    "FTP": True,
    "FTPS": True,
    "TFTP": True,
    "LOCAL": True,
    "7: NB-IoT": True,
    "41: Ethernet": True,
    "42: DSL": True,
    "43: PLC": True,
    "NB-IoT": True,
    "5G-NR TDD": True,
    "5G-NR FDD": True,
    "DSL": True,
    "PLC": True,
    "SMNC": True,
    "SMCC": True,
    "APN": True,
    "SSID": True,
    "SSH": True,
    "GSM RSSI": True,
    "USB WIFI": True,
    "TCP/IP": True,
    "WI-FI": True,
    "Wi-Fi": True,
    "IMEI": True,
    "Wifi Ap SSID": True,
    "Port": True,
    "Port:": True,
    "Port: %s": True,
    "Port (${PORT})": True,
    "GPRS": True,
    "USB": True,
    "BBA": True,
    # Locales
    "en_US": True,
    "fr_CA": True,
    "es_US": True,
    "it_IT": True,
    "nl_NL": True,
    "nb_NO": True,
    "sv_SE": True,
    "is_IS": True,
    "de_DE": True,
    "hu_HU": True,
    "da_DK": True,
    "ro_RO": True,
    "pt_PT": True,
    "fr_FR": True,
    # Countries
    "Andorra": True,
    "Angola": True,
    "Argentina": True,
    "Barbados": True,
    "Belize": True,
    "Benin": True,
    "Botswana": True,
    "Burkina Faso": True,
    "Burundi": True,
    "Chile": True,
    "Egypt": True,
    "Eritrea": True,
    "Gabon": True,
    "Ghana": True,
    "Grenada": True,
    "Guatemala": True,
    "Guinea": True,
    "Guinea-Bissau": True,
    "Guyana": True,
    "Haiti": True,
    "Honduras": True,
    "Kiribati": True,
    "Laos": True,
    "Lesotho": True,
    "Malawi": True,
    "Mali": True,
    "Malta": True,
    "Nauru": True,
    "Niger": True,
    "Palau": True,
    "Panama": True,
    "Paraguay": True,
    "Peru": True,
    "Portugal": True,
    "Rwanda": True,
    "Samoa": True,
    "San Marino": True,
    "Senegal": True,
    "Sierra Leone": True,
    "Togo": True,
    "Tonga": True,
    "Tuvalu": True,
    "Uganda": True,
    "Uruguay": True,
    "Vanuatu": True,
    "Venezuela": True,
    "Vietnam": True,
    "Zimbabwe": True,
    # Abbreviation
    "Ok": True,
    "OK": True,
    "Aux": True,
    "PTM": True,
    "Ok": True,
    "OK": True,
    "EULA": True,
    "E-mail": True,
    "Email": True,
    "PIR": True,
    "PGM": True,
    "ID": True,
    "CSV": True,
    "PDF": True,
    "URL": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    # Metric
    "V": True,
    "mA": True,
    "Ohm": True,
    "AM": True,
    "cid": True,
    "sia": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    "": True,
    # Variables
    "(%s)": True,
    # Other
    "Export": True,
    "Software": True,
    "Auto": True,
    "Test": True,
    "Firmware": True
}
